### ISSUE TITLE
Issue running dep deploy:live --publish

### ISSUE THREAD

**Issue by plondon** [radian-software/riju#106]
Hey! It seems I'm pretty close w/ self hosting after making a few changes (discussed [here](https://github.com/raxod502/riju/issues/103))

It seems I don't have sufficient privileges to run a deploy though? 

Running the deploy cmd results in:

<img width="951" alt="Screen Shot 2021-09-10 at 5 33 14 PM" src="https://user-images.githubusercontent.com/5640772/132922047-3d582b90-9ccd-44b2-ac4a-071b21f474e3.png">

Hopefully you have some insight into how to proceed? Thanks!

**Comment by raxod502** [comment]
This is because you need to run `make ecr` to authenticate to ECR using your AWS credentials before pushing and pulling will work. That should really happen automatically (https://github.com/raxod502/riju/issues/74), but in the meantime I pushed a commit (linked above) that adds this step to the self-hosting guide.
