### ISSUE TITLE
Riju frontend enhancement

### ISSUE THREAD

**Issue by inaseem** [radian-software/riju#91]
Hi, @raxod502 congrats on bringing Riju live again. I have spent a day recreating the Riju front end. 
Here is the demo URL. 
https://inaseem.gitlab.io/riju

**Improvements:**
1. Redesign the Home page
2. Redesign the Editor and Terminal page.
3. Added `Search` as scrolling to find a language option to click is a little tedious.
4. Added colors to terminal output.

**Additional:** (can be implemented/partially implemented)
1. Dark mode (turned off by default as this needs some more changes)
2. Editor and Terminal layouts.

**Note:** Clicking/selecting any language would open the JavaScript editor and terminal. It requires languages list from backend so for now its fixed for JavaScript. Also the option to switch language dropdown needs data so that is also on hold.

Screenshots:
**Home page**
![image](https://user-images.githubusercontent.com/6770106/127198755-643a21da-475d-4fa5-817d-bf6ee30915a9.png)

**Search**
![image](https://user-images.githubusercontent.com/6770106/127198864-5a3e73b8-fe3d-4a80-b52b-0313e6d5daa7.png)

**Editor page**
![image](https://user-images.githubusercontent.com/6770106/127182731-7c2d89c7-dadf-479a-b3ba-415ef9a76b01.png)

Looking forward to hearing from you.

**Comment by rayhanadev** [comment]
Woah! That's really cool.

**Comment by firefish111** [comment]
![moo](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Cow_female_black_white.jpg/1200px-Cow_female_black_white.jpg)
![no u](https://cdn.britannica.com/55/174255-050-526314B6/brown-Guernsey-cow.jpg)
![cow](https://static.dw.com/image/47863948_303.jpg)
![oof](https://cdn-a.william-reed.com/var/wrbm_gb_food_pharma/storage/images/publications/feed/feednavigator.com/article/2020/05/19/the-cow-favors-natural-over-synthetic-vitamin-e/11403541-1-eng-GB/The-cow-favors-natural-over-synthetic-vitamin-E.jpg)
![moo haha](https://images.unsplash.com/photo-1564085352725-08da0272627d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=668&q=80)
![cow monopoly](https://images.unsplash.com/photo-1595365691689-6b7b4e1970cf?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGNvd3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60)
![monopolistic behaviour](https://images.unsplash.com/photo-1502590464431-3b66d77494d7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=667&q=80)
![internet explorer](https://images.unsplash.com/photo-1574429678170-74c5eed2cc39?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80)

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [comment]
i rate it 12 cows out of 10 watermelons

**Comment by firefish111** [comment]
perfection

**Comment by inaseem** [comment]
@firefish111 Your cow images are cool 😄 . In the pervious build the UI was a cow with color(other than black and white). Removed the colors just 2 hours back, still it looks decent.

**Comment by firefish111** [comment]
oh no our cow army has been spotted

**Comment by firefish111** [comment]
i guess as we've been found, i must

https://cau-go-mu.firefish.repl.co

> for all other people who helped raid this issue: i must ssay this website is under construction

**Comment by inaseem** [comment]
@firefish111 The cow will have colors in around 20 minutes. It wont be all black and white. Enjoy.

**Comment by firefish111** [comment]
i didn't mean tha-

**Comment by inaseem** [comment]
@firefish111 Yeah, I misunderstood. Anyways nice cow images.

**Comment by raxod502** [comment]
@firefish111 @ch1ck3n-byte Please keep conversations on topic. I've marked your preceding comments as spam, and will report future such comments to GitHub Support.

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [comment]
bruh what part of me rating that upgrade was spam

**Comment by firefish111** [comment]
idk, respect their choices

**Comment by raxod502** [comment]
@ch1ck3n-byte Not to put too fine a point on it, but you posted nine hi-resolution photographs of cows, followed by eight subsequent comments discussing the cows. As far as I can tell, this bears no relationship whatsoever to the pull request under discussion or this repository itself, and as such I consider it off-topic/spam.

**Comment by firefish111** [comment]
eight pictures of cows

**Comment by inaseem** [comment]
Hey @raxod502 this front end enhancement is currently a separate repo hosted on GitLab. I wanted to get some feedback. Also if this could be replaced with the current front end it will be nice for the end user. Let me know what you think.

**Comment by raxod502** [comment]
Hey @inaseem, I'm sorry for taking so long to get back to you. I've been occupied by trying to get the underlying infrastructure for Riju stabilized under the load of additional users. Now that things are in a pretty good place, I can look at the issue tracker backlog.

As part of the infrastructure stabilization I made it so that LSP isn't enabled until the user explicitly requested it, and this change required some reworking of the frontend to add more interactivity. I took some inspiration from your design when doing this redesign, which you can see live at https://riju.codes/python.

Would you mind sharing a link to the code for your version of the frontend, or making a pull request? I wasn't able to find it.

One thing I wanted to flag was that I would prefer to avoid turning Riju into an [SPA](https://en.wikipedia.org/wiki/Single-page_application) or dynamically loading the HTML content. I don't have any objection to adding JavaScript to power things like a language search, but it should remain optional rather than being required simply to load a static list of languages. I think there's a great middle ground between the current state and what you have that would be a big improvement, nonetheless.

**Comment by inaseem** [comment]
Hi @raxod502, thank you for the comment above. I understand that stabilizing the core is the hardest of all. 
Great job on doing the hardest parts and the UI improvements. It looks good. 

The link that I have shared above was an SPA (create react app). And it uses material-ui (CSS in JS) for all the styling. I understand the concerns around SPA. Also the SPA version takes a while to load the webpage. Keeping those things and new features in mind I have migrated all the existing code to Next JS(server side generation).

I am not creating a PR as of now as I think that there a few backend changes which are also required. The backend changes would mostly be the addition of 2 routes. 

1. getting list of all languages.
2. getting the details of a single language.

These would be consumed by the Next JS pages on server. 

Link for the repo: https://gitlab.com/inaseem/riju

Answers to some expected questions:
**Q. Cant we just add CSS to the existing cjs files.**
Ans: I am not very familiar working with CJS. Although I tried, but ran into some issues.
**Q. Why use Next, React or any front end framework.**
Ans: I went through the existing front end code, yes there may not be a need to any of the React/Next etc. Adding React was a personal preference. Your comment above isn't very welcoming to the SPA approach so I found a common ground with Next JS where it's not an SPA and still uses React. Moreover this simplifies the structure of the app and addition of features would be much more simpler.

Please let me know If this is not something which can serve riju's front end requirements.
I also have a few ideas for the editor page which I will try to implement next.

**Comment by raxod502** [comment]
Thanks for sharing the repo! I looked through the code, and I like that things are split into multiple files. And I've seen in past projects that the plain JavaScript approach can face scalability problems once the UI becomes sufficiently complex, so it seems reasonable to try to mitigate those concerns using React, which I've used with reasonable success in the past.

In light of that, I think this change would be a welcome improvement, as long as it doesn't increase the code complexity too tremendously.

> I think that there a few backend changes which are also required

I'm curious about why these are needed. In the current implementation, the server embeds this information (the list of languages, for the index page, and the details of a single language, for the editor page) directly into the JavaScript served to the client:

https://github.com/raxod502/riju/blob/15f959bbeb62b4db985c57a814751f69d880a4a8/frontend/pages/app.ejs#L21-L23
https://github.com/raxod502/riju/blob/15f959bbeb62b4db985c57a814751f69d880a4a8/frontend/pages/index.ejs#L13-L20

This feels better to me since there is no need for another round-trip API call to the server. Does Next.js not support dynamic templating?

The above notwithstanding, per https://github.com/raxod502/riju/issues/90 it would actually be better to serve the frontend as a fully static website, which would make it impossible to rely on dynamic templating. So in that case we would need to do things the way you're suggesting anyways.

In light of that, I don't see any reason why these API routes can't be added.

**Comment by rayhanadev** [comment]
@radox502 

> Does Next.js not support dynamic templating?

Next.js is actually serverless, and while you *can* run a custom server you can't do something like EJS, which you currently have. A small change might have to be made to the API to get that running.

I would think maybe two API routes:
- `/data/languages`: fetch metadata about all languages
- `/data/languages/:name`: fetch metadata about one language

Then Next.js can use getStaticProps (i.e. fetch the data during build phase) so that the data is baked into the site.

**Comment by inaseem** [comment]
Hey @raxod502 as mentioned by @RayhanADev we can have a custom server, but templating like EJS isn't out of box. For now I have moved the logic to `getStaticProps` for pre rendering of pages at build time. We only needs the `langs` object at build time to generate static pages for all languages. These changes are available at https://inaseem.gitlab.io/riju/ with all language links and search working.

The only issue with getStaticProps is that after we have created a build and released, any new additions to langs object would only be generated in a new build. In a way we would have to manually build and release on each new language addition. If we instead fetch the list of languages and language details using an API route on `getInitialProps` or `getServerSideProps` then any new additions to langs would not require a rebuild/release of the frontend unless there are front end changes.

**Comment by raxod502** [comment]
Yeah, as much as it pains me to make a site dynamically loaded when it could be static, it does make sense to remove the dependency of the frontend on the backend language list.

Having thought it over, I think we should add API routes for fetching the language list, and populate dynamically. We already require JavaScript for the main application to work, so requiring it for the main page I guess isn't the worst thing.

**Comment by inaseem** [comment]
Hi @raxod502 , I have forked and added the changes to front end folder. It's currently in a `enhancement/frontend` branch. You can try running it locally to test the changes.  If you could please create a branch with the same name in your repo, then I will be able to create a pull request on that branch. Which can later merge with master. 

Few additional improvements:
1. Removed setTimeout for reconnecting. If only there is a change in editor then the reconnection will happen which would also update the status to idle->connecting->connected

Here is the link to the same branch on the forked repo. https://github.com/inaseem/riju/tree/enhancement/frontend
Changes can also be seen live [here](https://inaseem.gitlab.io/riju)

Instruction for running locally, 
1. yarn build
2. yarn start

If you want to check the dev build(it runs very slowly). You can simply go with `yarn dev`

**Comment by inaseem** [comment]
UI improvements on the Editor page(mostly on the **controls on top**):

![image](https://user-images.githubusercontent.com/6770106/135722305-1849a15a-391e-401d-999b-97a2b6c3a801.png)

**Comment by inaseem** [comment]
**What's new?**
1. Added Layouts[vertical/horizontal split] for the editor
2. Redesigned the Navbar
3. Both the terminal and editor can can be resized using the drag handles[can be spotted in middle]

![image](https://user-images.githubusercontent.com/6770106/135764674-3ba00790-9cb3-4672-a4aa-885f9dea939b.png)

**Comment by rayhanadev** [comment]
Love it ❤️

**Comment by raxod502** [comment]
> If you could please create a branch with the same name in your repo, then I will be able to create a pull request on that branch

Hmm, not sure I understand this, you should be able to create a PR just fine regardless of the branch name---I've done so here: https://github.com/raxod502/riju/pull/126

Will close this issue so we can continue discussion there.
